image: golang:1.8

stages:
  - deploy


variables:
  GOSOURCES: "/go/src/ezcp.io/ezcp-server"

ezcp-server-deploy:
  stage: deploy
  script:
    - mkdir -p $GOSOURCES
    - cp -r . $GOSOURCES
    - cd $GOSOURCES
    - curl https://glide.sh/get | sh
    - glide install
    - go build -ldflags "-X main.Build=$CI_PIPELINE_ID -X main.Tag=$CI_BUILD_TAG -X main.BitgoToken=$BITGO_TOKEN -X main.BitgoWallet=$BITGO_WALLET"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$EZCP_IO_SSHKEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh chris@ezcp.io 'killall ezcp-server || true && rm -f /home/chris/ezcp/ezcp-server'
    - scp ezcp-server chris@ezcp.io:~/ezcp/
    - ssh chris@ezcp.io 'nohup ~/ezcp/ezcp-server -db localhost:27017 > /home/chris/ezcp/ezcp.log 2>&1 &'

  environment:
    name: ezcp.io
    url: https://ezcp.io
  only:
    - master